name: Deploy to zugriff.eu

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Python requirements
        run: pip install -r preparation/requirements.txt

      - name: Generate segments from Supabase
        run: python3 preparation/supa_splitter.py
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      
      - name: Move generated segments into frontend/static
        run: |
          mkdir -p frontend/static/segments
          cp -r preparation/segments/*.geojson frontend/static/segments/
          cp preparation/segments/segments_index.json frontend/static/segments/

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build project
        run: npm run build
        working-directory: frontend
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VOICEFLOW_API_KEY: ${{ secrets.VOICEFLOW_API_KEY }}

      - uses: zugriffcloud/action-deploy@latest
        with:
          deploymentToken: ${{ secrets.ZUGRIFF_DEPLOY_TOKEN }}
          cwd: frontend